### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by stone531** [segmentio/kafka-go#332]
**Describe the bug**
# github.com/segmentio/kafka-go
../../../github.com/segmentio/kafka-go/crc32.go:60:4: undefined: io.StringWriter

**Comment by achille-roussel** [comment]
Thanks for reporting the issue. 

io.StringWriter was introduced in Go 1.12, we used this interface in v0.3.0 of this package, the v0.2.x should work fine on Go 1.11. 

Is upgrading to Go 1.12 am option for you? Or do you need this issue to be patched in the library?

**Comment by ssenthil416** [comment]
-bash-4.2$ go get -u github.com/segmentio/kafka-go
# github.com/segmentio/kafka-go
../../../github.com/segmentio/kafka-go/crc32.go:60:4: undefined: io.StringWriter

**Comment by achille-roussel** [comment]
This was first reported in https://github.com/segmentio/kafka-go/issues/321

Please let us know if upgrading to Go 1.12 isn't an option.

**Comment by peterfroehlich** [comment]
It would be nice to have it patched... not that easy to update dependencies in some closed down production envs.

**Comment by achille-roussel** [comment]
We removed the use of `io.StringWriter` in the 0.3.x series starting 0.3.2.
